export const fruitCatalog = [
  { key: "apple", label: "Apple", image: "./images/fruits/apple.svg", back: "#f59e6c" },
  { key: "banana", label: "Banana", image: "./images/fruits/banana.svg", back: "#eab54c" },
  { key: "grape", label: "Grape", image: "./images/fruits/grape.svg", back: "#8a72ff" },
  { key: "orange", label: "Orange", image: "./images/fruits/orange.svg", back: "#fb8c55" },
  { key: "pear", label: "Pear", image: "./images/fruits/pear.svg", back: "#8ecf72" },
  { key: "peach", label: "Peach", image: "./images/fruits/peach.svg", back: "#ff9cab" },
  { key: "melon", label: "Melon", image: "./images/fruits/melon.svg", back: "#69c88a" },
  { key: "berry", label: "Berry", image: "./images/fruits/berry.svg", back: "#ef5d81" },
  { key: "cherry", label: "Cherry", image: "./images/fruits/cherry.svg", back: "#f35d6e" },
  { key: "kiwi", label: "Kiwi", image: "./images/fruits/kiwi.svg", back: "#8ebc4c" },
  { key: "lemon", label: "Lemon", image: "./images/fruits/lemon.svg", back: "#f5c94c" },
  { key: "lime", label: "Lime", image: "./images/fruits/lime.svg", back: "#5fcf7b" },
  { key: "mango", label: "Mango", image: "./images/fruits/mango.svg", back: "#ffa657" },
  { key: "plum", label: "Plum", image: "./images/fruits/plum.svg", back: "#7f63d8" },
  { key: "coconut", label: "Coconut", image: "./images/fruits/coconut.svg", back: "#b98b61" },
  { key: "pineapple", label: "Pineapple", image: "./images/fruits/pineapple.svg", back: "#d9af45" },
  { key: "strawberry", label: "Strawberry", image: "./images/fruits/strawberry.svg", back: "#f26c76" },
  { key: "watermelon", label: "Watermelon", image: "./images/fruits/watermelon.svg", back: "#59c977" },
];
